### ISSUE TITLE
Create Sign-In Page for Service Seeker

### ISSUE THREAD

**Issue by Ahzem** [Ahzem/Seyoni#10]
We need to create a sign-in page for service seekers based on the provided Figma prototype design. The page should use the icons in the assets/icons directory and implement the background using the background_widget.dart from the src/widgets directory. The form fields should be reusable components.

**Directory Structure**:
```
lib
│───main.dart    
└───src
    │───pages
    |    │──entry-pages
    |    │──signin-pages
    |    |     │──components
    |    |     |     │──form-fields.dart
    |    |     │──signin-page.dart
    │───widgets
```

**Task**:

- [ ] Create the sign-in page according to the provided Figma prototype design.

<table>
  <tr>
    <td>
      <img src="https://github.com/user-attachments/assets/955d6e7f-b5d6-4058-95a7-b9c1f98f7f98">
    </td>
  </tr>
</table>

- [ ] Use the icons from the assets/icons directory.
- [ ] Implement the background using the background_widget.dart widget.
- [ ] Save the sign-in page file as signin-page.dart in lib>src>pages>signin-pages.
- [ ] Save the form fields as reusable components in lib>src>pages>signin-pages>components>form-fields.dart.
- [ ] Ensure the code is well-organized and follows the project’s coding standards.
