### ISSUE TITLE
Create Bottom Navigation Bar

### ISSUE THREAD

**Issue by Ahzem** [Ahzem/Seyoni#22]
We need to create a bottom navigation bar based on the provided Figma design. Use the icons located in the assets/icons directory for the implementation. Save the navigation bar file in the widgets directory as specified below:

![Image](https://github.com/user-attachments/assets/64b9b85d-4a3a-461f-b2dc-2762129bcd78)

**Task**:

- [ ] Create a bottom navigation bar according to the provided Figma design.
- [ ] Use the icons from the assets/icons directory.
- [ ] Save the new Flutter file as navbar_widget.dart in lib>src>widgets.

```
lib
│───main.dart    
└───src
    │───widgets
    |    │──navbar_widget.dart
```

- [ ] Ensure the code is well-organized and follows the project’s coding standards.
