### ISSUE TITLE
Create a Sign-Up Page For Service Seeker

### ISSUE THREAD

**Issue by Ahzem** [Ahzem/Seyoni#23]
We need to create a sign-up page for service seekers based on the provided Figma prototype design. The page should use the icons in the assets/icons directory and implement the background using the background_widget.dart from the src/widgets directory. The form fields should be reusable components.

**Directory Structure**:
```
lib
│───main.dart    
└───src
    │───pages
    |    │──entry-pages
    |    │──signup-pages
    |    |     │──components
    |    |     |     │──form-fields.dart
    |    |     │──signup-page.dart
    │───widgets
```

**Task**:

- [ ] Create the sign-up page according to the provided Figma prototype design.

<table>
  <tr>
    <td>
      <img src="https://github.com/user-attachments/assets/084d8714-0ec8-478f-b20b-a98c32114260">
    </td>
  </tr>
</table>

- [ ] Use the icons from the assets/icons directory.
- [ ] Implement the background using the background_widget.dart widget.
- [ ] Save the sign-up page file as signup-page.dart in lib>src>pages>signup-pages.
- [ ] Save the form fields as reusable components in lib>src>pages>signup-pages>components>form-fields.dart.
- [ ] Ensure the code is well-organized and follows the project’s coding standards.
