### ISSUE TITLE
Implement Separate Route File

### ISSUE THREAD

**Issue by Ahzem** [Ahzem/Seyoni#25]
We need to implement a separate route.dart file to manage the routes in our application. The route.dart file should be created in the src/config directory. Update the navigation in other parts of the code to use the routes defined in this file.

**Directory Structure**:
```
lib
│───main.dart    
└───src
    │───config
    |    │──route.dart
    │───pages
    |    │──entry-pages
    |    │──signin-pages
    |    |     │──components
    |    |     |     │──form-fields.dart
    |    |     │──signin-page.dart
    |    │──signup-pages
    |    |     │──components
    |    |     |     │──form-fields.dart
    |    |     │──signup-page.dart
    │───widgets
```

**Task**:

- [ ] Create a new route.dart file in the lib>src>config directory.
- [ ] Define the routes for the application in the route.dart file.
- [ ] Update the navigation in other parts of the code to use the routes from route.dart.
- [ ] Ensure the code is well-organized and follows the project’s coding standards.
