### ISSUE TITLE
Design the Landing Pages Using Flutter

### ISSUE THREAD

**Issue by Ahzem** [Ahzem/Seyoni#7]
We have designed the landing pages in Figma and now need to implement these designs in Flutter. The task is to create the four landing pages based on the provided Figma designs.

**Task**:
- [x] Design the four landing pages using Flutter according to the Figma screenshots provided.
<table>
  <tr>
    <td>
      <img src="https://github.com/user-attachments/assets/8c325dba-5f99-4d60-be4a-309b5924848a">
    </td>
    <td>
      <img src="https://github.com/user-attachments/assets/63a10765-90a5-4955-8b5c-43fbea1b4a78">
    </td>
    <td>
      <img src="https://github.com/user-attachments/assets/9fe7903a-6760-4a01-80db-2981682521c1"> 
    </td>
  </tr>
</table>

- [x] Follow the directory structure: 
```
lib
│───main.dart    
└───src
    │───pages
    |    │──page1.dart
    |    │──page3.dart
    |    └──page4.dart
```
- [x] Ensure the code is well-organized and adheres to the project’s coding standards.
